### ISSUE TITLE
use Solid Application Data Discovery

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-profile-ui#15]
https://github.com/solid/solid-profile-ui/blob/3b6ec5ab4b01fd97eab1b117ac02705bb0c495ce/assets/scripts/models/profile.js#L35

Line above seems to assume `/profile/` in URI. If someone used different profile editor it might have created different path. Shouldn't profile editor also use [Solid Application Data Discovery](https://github.com/solid/solid/blob/master/proposals/data-discovery.md) and not make any special assumptions about URI patterns?

**Comment by deiu** [comment]
Thanks for raising this issue. We'll address it asap.

**Comment by deiu** [comment]
Fixed in 69b4402fd6512567e4f16ef365779428808a82a8
