### ISSUE TITLE
error check on email field

### ISSUE THREAD

**Issue by ebporter** [solid/solid-profile-ui#17]
In new profile builder (https://solid.github.io/solid-profile-ui/), the email field should error check for email format. In other words, if I enter data that does not appear to be in email format (just ebporter, no @gmail.com), it should give you feedback:

"You have entered something that does not appear to be in email format. Would you like to correct it?"

I think we could allow people to have non-well-formatted data for this field, but we should warn them.

**Comment by dan-f** [comment]
:+1: I added a TODO for this but just haven't gotten around yet. I think this is a good thing to add once tests are in place.

**Comment by dan-f** [comment]
Closed in favor of #19
